"""
Enriched Context Manager
Preserves ALL strategic, creative, and planning data generated by EmailPilot Simple
that may not be directly compatible with calendar import specifications.

This module ensures complete data preservation for post-review brief generation.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict

logger = logging.getLogger(__name__)


@dataclass
class StrategicContext:
    """Strategic rationales and decision-making context"""
    send_time_rationale: Optional[str] = None
    targeting_rationale: Optional[str] = None
    ab_test_hypothesis: Optional[str] = None
    campaign_sequence_rationale: Optional[str] = None
    seasonal_timing_strategy: Optional[str] = None


@dataclass
class CreativeBrief:
    """Complete creative direction and content specifications"""
    hero_section: Optional[Dict[str, Any]] = None
    body_copy: Optional[Dict[str, Any]] = None
    cta_strategy: Optional[Dict[str, Any]] = None
    visual_assets: Optional[Dict[str, Any]] = None
    brand_guidelines: Optional[Dict[str, str]] = None


@dataclass
class CrossChannelContent:
    """Content for channels beyond the primary campaign"""
    sms_message: Optional[str] = None
    push_notification: Optional[str] = None
    in_app_message: Optional[str] = None
    social_media_copy: Optional[str] = None


@dataclass
class PlanningMetadata:
    """Strategic planning and scheduling context"""
    week_number: Optional[int] = None
    campaign_sequence_position: Optional[int] = None
    total_campaigns_in_period: Optional[int] = None
    dependencies: Optional[List[str]] = None
    related_campaigns: Optional[List[str]] = None


@dataclass
class EnrichedEventContext:
    """Complete enriched context for a single calendar event"""
    event_id: str
    calendar_event_name: str
    strategic_context: StrategicContext
    creative_brief: CreativeBrief
    cross_channel_content: CrossChannelContent
    planning_metadata: PlanningMetadata
    raw_simplified_event: Optional[Dict[str, Any]] = None
    raw_detailed_campaign: Optional[Dict[str, Any]] = None


class EnrichedContextManager:
    """
    Manages preservation and retrieval of enriched context data
    that extends beyond calendar import specifications.
    """

    def __init__(self, output_dir: str = "./outputs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_event_id(self, client_name: str, date: str, title: str) -> str:
        """
        Generate unique event ID from campaign components

        Args:
            client_name: Client identifier (e.g., 'rogue-creamery')
            date: Campaign date (YYYY-MM-DD)
            title: Campaign title

        Returns:
            Unique event ID (e.g., 'rogue-creamery-2025-12-02-holiday-gift-guide')
        """
        # Create URL-safe slug from title
        slug = title.lower()
        slug = slug.replace("'", "")
        slug = "".join(c if c.isalnum() or c == " " else "" for c in slug)
        slug = "-".join(slug.split())[:50]  # Limit length

        return f"{client_name}-{date}-{slug}"

    def extract_strategic_context(
        self,
        simplified_event: Dict[str, Any],
        detailed_campaign: Optional[Dict[str, Any]] = None
    ) -> StrategicContext:
        """
        Extract all strategic rationales and hypotheses

        Args:
            simplified_event: Event from simplified calendar
            detailed_campaign: Corresponding campaign from detailed calendar

        Returns:
            StrategicContext object with all strategic data
        """
        context = StrategicContext()

        # From simplified calendar
        if "ab_test_idea" in simplified_event:
            context.ab_test_hypothesis = simplified_event["ab_test_idea"]

        # From detailed calendar (if available)
        if detailed_campaign:
            context.send_time_rationale = detailed_campaign.get("send_time_rationale")

            if "audience" in detailed_campaign:
                context.targeting_rationale = detailed_campaign["audience"].get("targeting_rationale")

            if "content" in detailed_campaign and "subject_lines" in detailed_campaign["content"]:
                test_hyp = detailed_campaign["content"]["subject_lines"].get("test_hypothesis")
                if test_hyp and not context.ab_test_hypothesis:
                    context.ab_test_hypothesis = test_hyp

        return context

    def extract_creative_brief(
        self,
        simplified_event: Dict[str, Any],
        detailed_campaign: Optional[Dict[str, Any]] = None
    ) -> CreativeBrief:
        """
        Extract complete creative direction and specifications

        Args:
            simplified_event: Event from simplified calendar
            detailed_campaign: Corresponding campaign from detailed calendar

        Returns:
            CreativeBrief object with all creative specifications
        """
        brief = CreativeBrief()

        # Hero section from simplified calendar
        hero_section = {}
        if "hero_h1" in simplified_event:
            hero_section["headline"] = simplified_event["hero_h1"]
        if "sub_head" in simplified_event:
            hero_section["subheadline"] = simplified_event["sub_head"]
        if "hero_image" in simplified_event:
            hero_section["hero_image_description"] = simplified_event["hero_image"]
            # Extract filename if present
            if "hero_image" in simplified_event and ".jpg" in simplified_event["hero_image"]:
                parts = simplified_event["hero_image"].split(" - ")
                if len(parts) > 0 and ".jpg" in parts[0]:
                    hero_section["hero_image_filename"] = parts[0].strip()

        if hero_section:
            brief.hero_section = hero_section

        # From detailed calendar (if available)
        if detailed_campaign and "content" in detailed_campaign:
            content = detailed_campaign["content"]

            # Enhanced hero section
            if "hero_section" in content:
                detailed_hero = content["hero_section"]
                if not brief.hero_section:
                    brief.hero_section = {}
                brief.hero_section.update({
                    "headline": detailed_hero.get("headline", brief.hero_section.get("headline")),
                    "subheadline": detailed_hero.get("subheadline", brief.hero_section.get("subheadline"))
                })

                if "hero_image" in detailed_hero:
                    brief.hero_section["hero_image_description"] = detailed_hero["hero_image"].get("description")
                    brief.hero_section["hero_image_filename"] = detailed_hero["hero_image"].get("filename")
                    brief.hero_section["hero_image_alt_text"] = detailed_hero["hero_image"].get("alt_text")

            # Body copy
            if "body" in content:
                brief.body_copy = {
                    "main_message": content["body"].get("main_copy"),
                    "supporting_points": content["body"].get("supporting_points", [])
                }

            # CTA strategy
            if "cta" in content:
                brief.cta_strategy = {
                    "primary": {
                        "text": content["cta"].get("primary_text"),
                        "url": content["cta"].get("primary_url")
                    }
                }
                if "secondary_text" in content["cta"]:
                    brief.cta_strategy["secondary"] = {
                        "text": content["cta"].get("secondary_text"),
                        "url": content["cta"].get("secondary_url")
                    }

        # CTA from simplified calendar (if not from detailed)
        if not brief.cta_strategy and "cta_copy" in simplified_event:
            brief.cta_strategy = {
                "primary": {
                    "text": simplified_event["cta_copy"],
                    "url": None  # URL not in simplified format
                }
            }

        return brief

    def extract_cross_channel_content(
        self,
        simplified_event: Dict[str, Any]
    ) -> CrossChannelContent:
        """
        Extract cross-channel message variants

        Args:
            simplified_event: Event from simplified calendar

        Returns:
            CrossChannelContent object
        """
        return CrossChannelContent(
            sms_message=simplified_event.get("secondary_message"),
            push_notification=simplified_event.get("push_notification"),
            in_app_message=simplified_event.get("in_app_message"),
            social_media_copy=simplified_event.get("social_copy")
        )

    def extract_planning_metadata(
        self,
        simplified_event: Dict[str, Any],
        campaign_index: int,
        total_campaigns: int
    ) -> PlanningMetadata:
        """
        Extract strategic planning metadata

        Args:
            simplified_event: Event from simplified calendar
            campaign_index: Position in campaign sequence (0-indexed)
            total_campaigns: Total campaigns in period

        Returns:
            PlanningMetadata object
        """
        return PlanningMetadata(
            week_number=simplified_event.get("week_number"),
            campaign_sequence_position=campaign_index + 1,
            total_campaigns_in_period=total_campaigns,
            dependencies=simplified_event.get("dependencies", []),
            related_campaigns=simplified_event.get("related_campaigns", [])
        )

    def create_enriched_context(
        self,
        client_name: str,
        simplified_calendar: Dict[str, Any],
        detailed_calendar: Optional[Dict[str, Any]] = None,
        context_key: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Create complete enriched context from simplified and detailed calendars

        Args:
            client_name: Client identifier
            simplified_calendar: Simplified calendar JSON (import format)
            detailed_calendar: Detailed calendar JSON (full context)
            context_key: Optional custom key (auto-generated if not provided)

        Returns:
            Complete enriched context structure
        """
        events = simplified_calendar.get("events", [])
        total_campaigns = len(events)

        # Generate context key if not provided
        if not context_key:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            start_date = events[0].get("date", "unknown") if events else "unknown"
            end_date = events[-1].get("date", "unknown") if events else "unknown"
            context_key = f"{client_name}_{start_date}_{end_date}_{timestamp}"

        # Build detailed campaign lookup
        detailed_campaigns = {}
        if detailed_calendar and "campaigns" in detailed_calendar:
            for camp in detailed_calendar["campaigns"]:
                name = camp.get("name", "")
                detailed_campaigns[name] = camp

        # Extract enriched context for each event
        enriched_events = {}

        for idx, event in enumerate(events):
            event_id = self.generate_event_id(
                client_name,
                event.get("date", ""),
                event.get("title", "")
            )

            # Find matching detailed campaign
            detailed_campaign = detailed_campaigns.get(event.get("title"))

            enriched_event = EnrichedEventContext(
                event_id=event_id,
                calendar_event_name=event.get("title", ""),
                strategic_context=self.extract_strategic_context(event, detailed_campaign),
                creative_brief=self.extract_creative_brief(event, detailed_campaign),
                cross_channel_content=self.extract_cross_channel_content(event),
                planning_metadata=self.extract_planning_metadata(event, idx, total_campaigns),
                raw_simplified_event=event,
                raw_detailed_campaign=detailed_campaign
            )

            enriched_events[event_id] = enriched_event

        # Build complete enriched context structure
        enriched_context = {
            "enriched_context_key": context_key,
            "generated_at": datetime.now().isoformat(),
            "client_name": client_name,
            "date_range": {
                "start": events[0].get("date") if events else None,
                "end": events[-1].get("date") if events else None
            },
            "total_events": total_campaigns,
            "source_files": {
                "simplified_calendar": f"Loaded from memory",
                "detailed_calendar": f"Loaded from memory" if detailed_calendar else None
            },
            "events": {
                event_id: self._event_to_dict(event_context)
                for event_id, event_context in enriched_events.items()
            }
        }

        return enriched_context

    def _event_to_dict(self, event_context: EnrichedEventContext) -> Dict[str, Any]:
        """Convert EnrichedEventContext to dictionary for JSON serialization"""
        result = {
            "event_id": event_context.event_id,
            "calendar_event_name": event_context.calendar_event_name,
            "strategic_context": asdict(event_context.strategic_context),
            "creative_brief": asdict(event_context.creative_brief),
            "cross_channel_content": asdict(event_context.cross_channel_content),
            "planning_metadata": asdict(event_context.planning_metadata)
        }

        # Include raw data if present
        if event_context.raw_simplified_event:
            result["raw_simplified_event"] = event_context.raw_simplified_event
        if event_context.raw_detailed_campaign:
            result["raw_detailed_campaign"] = event_context.raw_detailed_campaign

        return result

    def save_enriched_context(
        self,
        enriched_context: Dict[str, Any],
        filename: Optional[str] = None
    ) -> Path:
        """
        Save enriched context to JSON file

        Args:
            enriched_context: Complete enriched context structure
            filename: Optional custom filename

        Returns:
            Path to saved file
        """
        if not filename:
            context_key = enriched_context.get("enriched_context_key", "unknown")
            filename = f"{context_key}_enriched_context.json"

        filepath = self.output_dir / filename

        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(enriched_context, f, indent=2, ensure_ascii=False)

        logger.info(f"Saved enriched context to: {filepath}")
        return filepath

    def load_enriched_context(self, context_key: str) -> Optional[Dict[str, Any]]:
        """
        Load enriched context by key

        Args:
            context_key: Enriched context identifier

        Returns:
            Enriched context structure or None if not found
        """
        filename = f"{context_key}_enriched_context.json"
        filepath = self.output_dir / filename

        if not filepath.exists():
            logger.warning(f"Enriched context not found: {filepath}")
            return None

        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)

    def get_event_enriched_context(
        self,
        context_key: str,
        event_id: str
    ) -> Optional[Dict[str, Any]]:
        """
        Get enriched context for a specific event

        Args:
            context_key: Enriched context identifier
            event_id: Event identifier

        Returns:
            Event enriched context or None if not found
        """
        enriched_context = self.load_enriched_context(context_key)
        if not enriched_context:
            return None

        events = enriched_context.get("events", {})
        return events.get(event_id)

    def merge_with_reviewed_calendar(
        self,
        reviewed_calendar: Dict[str, Any],
        context_key: str
    ) -> List[Dict[str, Any]]:
        """
        Merge human-reviewed calendar with enriched context for final brief generation

        Args:
            reviewed_calendar: Calendar JSON after human review/editing
            context_key: Enriched context identifier

        Returns:
            List of merged event objects ready for brief generation
        """
        enriched_context = self.load_enriched_context(context_key)
        if not enriched_context:
            logger.warning(f"No enriched context found for key: {context_key}")
            return []

        merged_events = []

        for event in reviewed_calendar.get("events", []):
            event_id = event.get("id")
            if not event_id:
                logger.warning("Event missing ID, skipping merge")
                continue

            # Get enriched context for this event
            enriched = enriched_context["events"].get(event_id, {})

            # Merge: reviewed calendar takes precedence, enriched fills gaps
            merged = {
                "calendar_data": event,  # Human-reviewed data
                "enriched_context": enriched,  # Preserved AI-generated context
                "event_id": event_id,
                "merged_at": datetime.now().isoformat()
            }

            merged_events.append(merged)

        return merged_events


# Example usage
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    # Example: Create enriched context from simplified calendar
    manager = EnrichedContextManager()

    # Load simplified calendar (example)
    simplified_calendar_path = Path("./outputs/rogue-creamery_2025-12-01_2025-12-31_20251116_013424_calendar_simplified.json")
    if simplified_calendar_path.exists():
        with open(simplified_calendar_path, 'r') as f:
            simplified_calendar = json.load(f)

        # Load detailed calendar (example)
        detailed_calendar_path = Path("./outputs/rogue-creamery_2025-12-01_2025-12-31_20251116_013424_calendar_detailed.json")
        detailed_calendar = None
        if detailed_calendar_path.exists():
            with open(detailed_calendar_path, 'r') as f:
                detailed_calendar = json.load(f)

        # Create enriched context
        enriched = manager.create_enriched_context(
            client_name="rogue-creamery",
            simplified_calendar=simplified_calendar,
            detailed_calendar=detailed_calendar,
            context_key="rogue-creamery_2025-12-01_2025-12-31_20251116_013424"
        )

        # Save to file
        saved_path = manager.save_enriched_context(enriched)
        print(f"Enriched context saved to: {saved_path}")

        # Example: Retrieve specific event enriched context
        event_context = manager.get_event_enriched_context(
            context_key="rogue-creamery_2025-12-01_2025-12-31_20251116_013424",
            event_id="rogue-creamery-2025-12-02-the-2025-holiday-gift-guide"
        )
        if event_context:
            print(f"\nRetrieved enriched context for event")
            print(f"Strategic context: {event_context['strategic_context']}")
